general:
  tagging_profile: metal

rules:
  file: data/rules.json

concepts:
  text_concepts_file: data/text-concepts.metal.json
  text_concepts_templates_file: data/text-concepts.templates.metal.json
  images_dir: images
