"""embeddings index

Revision ID: 18ec91d67615
Revises: c26ed170fb23
Create Date: 2026-04-13 10:41:54.625236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ec91d67615'
down_revision: Union[str, Sequence[str], None] = 'c26ed170fb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_embeddings_embedding'), 'embeddings', ['embedding'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_embedding'), table_name='embeddings')
    # ### end Alembic commands ###
