"""Added ollama descriptions table

Revision ID: 1d0b68c811bc
Revises: c2a127be6306
Create Date: 2026-04-01 17:01:09.153226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0b68c811bc'
down_revision: Union[str, Sequence[str], None] = 'c2a127be6306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ollama_description',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ollama_description_id'), 'ollama_description', ['id'], unique=False)
    op.create_index(op.f('ix_ollama_description_image_id'), 'ollama_description', ['image_id'], unique=False)
    op.drop_table('tmp_images_and_concepts')
    op.drop_table('tmp_concepts_to_images_matches')
    op.drop_table('tmp_images_to_concept_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_images_to_concept_matches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matches_count', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('tmp_concepts_to_images_matches',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matches_count', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('tmp_images_and_concepts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_ollama_description_image_id'), table_name='ollama_description')
    op.drop_index(op.f('ix_ollama_description_id'), table_name='ollama_description')
    op.drop_table('ollama_description')
    # ### end Alembic commands ###
