"""fix embeddings.embedding index — btree provides no acceleration for cosine_distance

Revision ID: b4e1a9c7d3f2
Revises: a3f9c1d8b6e2
Create Date: 2026-07-16

"""
from alembic import op

revision = 'b4e1a9c7d3f2'
down_revision = 'a3f9c1d8b6e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The original index (18ec91d67615_embeddings_index.py) was an unedited
    # autogenerated migration — SQLAlchemy's default index=True falls back
    # to a plain btree, which provides zero acceleration for pgvector's
    # cosine_distance() (<=>) operator used by get_similar's
    # ORDER BY ... LIMIT k query; it's dead weight on every write instead.
    # CONCURRENTLY avoids taking a blocking lock on this live, populated
    # table during the rebuild (build_image_embeddings.py writes to it
    # continuously) — which requires running outside Alembic's normal
    # per-migration transaction, hence autocommit_block().
    with op.get_context().autocommit_block():
        op.execute(
            "CREATE INDEX CONCURRENTLY ix_embeddings_embedding_hnsw_cosine "
            "ON embeddings USING hnsw (embedding vector_cosine_ops)"
        )
        op.execute("DROP INDEX CONCURRENTLY ix_embeddings_embedding")


def downgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute(
            "CREATE INDEX CONCURRENTLY ix_embeddings_embedding "
            "ON embeddings (embedding)"
        )
        op.execute("DROP INDEX CONCURRENTLY ix_embeddings_embedding_hnsw_cosine")
