"""add flagged_reason to image_extras

Revision ID: 29a039fa4457
Revises: 67d11660282b
Create Date: 2026-09-26 01:22:52.431465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a039fa4457'
down_revision: Union[str, Sequence[str], None] = '67d11660282b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_extras', sa.Column('flagged_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_extras', 'flagged_reason')
    # ### end Alembic commands ###
