"""add composite index for Image

Revision ID: 5434ca9a2c7a
Revises: b68b18f09246
Create Date: 2026-02-25 19:20:08.276753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5434ca9a2c7a'
down_revision: Union[str, Sequence[str], None] = 'b68b18f09246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.create_index('ix_images_created_at_id_desc', 'images', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_created_at_id_desc', table_name='images')
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    # ### end Alembic commands ###
