"""Fix tags table relationship

Revision ID: 6425c7d32f8d
Revises: 2a618c3f1655
Create Date: 2026-03-09 12:56:37.998543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6425c7d32f8d'
down_revision: Union[str, Sequence[str], None] = '2a618c3f1655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
