"""Trends sourcing models - fix - re-add as string

Revision ID: 65281efbcb60
Revises: 972d165a99fb
Create Date: 2026-04-24 23:42:25.109967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65281efbcb60'
down_revision: Union[str, Sequence[str], None] = '972d165a99fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trends_runs', 'status',
               existing_type=postgresql.ENUM('started', 'completed', 'failed', name='runstatus1'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trends_runs', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('started', 'completed', 'failed', name='runstatus1'),
               existing_nullable=False)
    # ### end Alembic commands ###
