"""precomputed duplicates table added

Revision ID: 682bae27645e
Revises: 18ec91d67615
Create Date: 2026-04-13 19:51:07.127169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682bae27645e'
down_revision: Union[str, Sequence[str], None] = '18ec91d67615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_duplicates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id1', sa.UUID(), nullable=True),
    sa.Column('image_id2', sa.UUID(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id1'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id2'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tmp_duplicates_id'), 'tmp_duplicates', ['id'], unique=False)
    op.create_index(op.f('ix_tmp_duplicates_image_id1'), 'tmp_duplicates', ['image_id1'], unique=False)
    op.create_index(op.f('ix_tmp_duplicates_image_id2'), 'tmp_duplicates', ['image_id2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tmp_duplicates_image_id2'), table_name='tmp_duplicates')
    op.drop_index(op.f('ix_tmp_duplicates_image_id1'), table_name='tmp_duplicates')
    op.drop_index(op.f('ix_tmp_duplicates_id'), table_name='tmp_duplicates')
    op.drop_table('tmp_duplicates')
    # ### end Alembic commands ###
