"""Clusters table

Revision ID: 6c2a2d7623c5
Revises: d083e250e6a6
Create Date: 2026-04-18 20:21:34.147584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2a2d7623c5'
down_revision: Union[str, Sequence[str], None] = 'd083e250e6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tmp_clusters_id'), 'tmp_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_tmp_clusters_image_id'), 'tmp_clusters', ['image_id'], unique=False)
    op.drop_column('tmp_duplicates', 'cluster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmp_duplicates', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tmp_clusters_image_id'), table_name='tmp_clusters')
    op.drop_index(op.f('ix_tmp_clusters_id'), table_name='tmp_clusters')
    op.drop_table('tmp_clusters')
    # ### end Alembic commands ###
