"""add image_classifications table

Revision ID: 6f770efe4fb4
Revises: a545480b9388
Create Date: 2026-09-15 21:00:15.304294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f770efe4fb4'
down_revision: Union[str, Sequence[str], None] = 'a545480b9388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_classifications',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('classifier', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', 'classifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_classifications')
    # ### end Alembic commands ###
