"""concept entities added

Revision ID: 8baa8880ed6b
Revises: 6425c7d32f8d
Create Date: 2026-03-22 15:15:14.952466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '8baa8880ed6b'
down_revision: Union[str, Sequence[str], None] = '6425c7d32f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_image_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('directory', sa.String(), nullable=True),
    sa.Column('centroid_embedding', VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_text_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('centroid_embedding', VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_image_set_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('embedding', VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['concept_image_set_id'], ['concept_image_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_text_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('embedding', VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['concept_text_set_id'], ['concept_text_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_texts')
    op.drop_table('concept_images')
    op.drop_table('concept_text_sets')
    op.drop_table('concept_image_sets')
    # ### end Alembic commands ###
