"""Add image extras table

Revision ID: 957d8e420fd5
Revises: 1d0b68c811bc
Create Date: 2026-04-07 13:04:13.660840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957d8e420fd5'
down_revision: Union[str, Sequence[str], None] = '1d0b68c811bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_extras',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_image_extras_image_id'), 'image_extras', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_extras_image_id'), table_name='image_extras')
    op.drop_table('image_extras')
    # ### end Alembic commands ###
