"""Trends sourcing models - fix - re-add

Revision ID: 972d165a99fb
Revises: ed163efa0fa9
Create Date: 2026-04-24 23:17:10.583470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972d165a99fb'
down_revision: Union[str, Sequence[str], None] = 'ed163efa0fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # sa.Enum(name='runstatus').drop(op.get_bind())

    runstatus1 = sa.Enum('started', 'completed', 'failed', name='runstatus1', create_constraint=False)
    # runstatus.create(op.get_bind())  # create the PG type first
    # runstatus = sa.Enum(name='runstatus', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('trends_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', runstatus1, nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('trends_run_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trends_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['feed_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends_run_results')
    op.drop_table('trends_runs')
    # ### end Alembic commands ###
    sa.Enum(name='runstatus1').drop(op.get_bind())
