"""add image_description_feedback table

Revision ID: a3c5a66c01c0
Revises: b4e1a9c7d3f2
Create Date: 2026-07-19 13:25:26.726780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c5a66c01c0'
down_revision: Union[str, Sequence[str], None] = 'b4e1a9c7d3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_description_feedback',
    sa.Column('image_description_id', sa.UUID(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_description_id'], ['image_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_description_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_description_feedback')
    # ### end Alembic commands ###
