"""add something

Revision ID: b4df248964cf
Revises: 5434ca9a2c7a
Create Date: 2026-03-07 13:07:29.569083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = 'b4df248964cf'
down_revision: Union[str, Sequence[str], None] = '5434ca9a2c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('embedding', VECTOR(dim=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('embeddings', sa.Column('embedding', VECTOR(dim=512), nullable=True))
    op.drop_column('embeddings', 'text')
    op.drop_column('embeddings', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('embeddings', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('embeddings', 'embedding')
    op.drop_table('concepts')
    # ### end Alembic commands ###
