"""add indexes

Revision ID: b68b18f09246
Revises: b273d186807b
Create Date: 2026-02-25 19:11:28.103668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68b18f09246'
down_revision: Union[str, Sequence[str], None] = 'b273d186807b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_embeddings_image_id'), 'embeddings', ['image_id'], unique=False)
    op.create_index(op.f('ix_image_metrics_image_id'), 'image_metrics', ['image_id'], unique=False)
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_texts_id'), 'ocr_texts', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_texts_image_id'), 'ocr_texts', ['image_id'], unique=False)
    op.create_index(op.f('ix_processing_errors_id'), 'processing_errors', ['id'], unique=False)
    op.create_index(op.f('ix_processing_errors_image_id'), 'processing_errors', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_errors_image_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_ocr_texts_image_id'), table_name='ocr_texts')
    op.drop_index(op.f('ix_ocr_texts_id'), table_name='ocr_texts')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.drop_index(op.f('ix_image_metrics_image_id'), table_name='image_metrics')
    op.drop_index(op.f('ix_embeddings_image_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    # ### end Alembic commands ###
