"""Clusters table - cluster id

Revision ID: b8f9e7218eee
Revises: 6c2a2d7623c5
Create Date: 2026-04-18 21:05:49.876353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f9e7218eee'
down_revision: Union[str, Sequence[str], None] = '6c2a2d7623c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmp_clusters', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tmp_clusters_cluster_id'), 'tmp_clusters', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tmp_clusters_cluster_id'), table_name='tmp_clusters')
    op.drop_column('tmp_clusters', 'cluster_id')
    # ### end Alembic commands ###
