"""concept entities added - cascade delete

Revision ID: c2a127be6306
Revises: 8baa8880ed6b
Create Date: 2026-03-24 16:34:58.185958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a127be6306'
down_revision: Union[str, Sequence[str], None] = '8baa8880ed6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('concept_image_sets_concept_id_fkey'), 'concept_image_sets', type_='foreignkey')
    op.create_foreign_key(None, 'concept_image_sets', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('concept_images_concept_image_set_id_fkey'), 'concept_images', type_='foreignkey')
    op.create_foreign_key(None, 'concept_images', 'concept_image_sets', ['concept_image_set_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('concept_text_sets_concept_id_fkey'), 'concept_text_sets', type_='foreignkey')
    op.create_foreign_key(None, 'concept_text_sets', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('concept_texts_concept_text_set_id_fkey'), 'concept_texts', type_='foreignkey')
    op.create_foreign_key(None, 'concept_texts', 'concept_text_sets', ['concept_text_set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'concept_texts', type_='foreignkey')
    op.create_foreign_key(op.f('concept_texts_concept_text_set_id_fkey'), 'concept_texts', 'concept_text_sets', ['concept_text_set_id'], ['id'])
    op.drop_constraint(None, 'concept_text_sets', type_='foreignkey')
    op.create_foreign_key(op.f('concept_text_sets_concept_id_fkey'), 'concept_text_sets', 'concepts', ['concept_id'], ['id'])
    op.drop_constraint(None, 'concept_images', type_='foreignkey')
    op.create_foreign_key(op.f('concept_images_concept_image_set_id_fkey'), 'concept_images', 'concept_image_sets', ['concept_image_set_id'], ['id'])
    op.drop_constraint(None, 'concept_image_sets', type_='foreignkey')
    op.create_foreign_key(op.f('concept_image_sets_concept_id_fkey'), 'concept_image_sets', 'concepts', ['concept_id'], ['id'])
    # ### end Alembic commands ###
