"""Trends sourcing models - fix run status 2

Revision ID: cddcbebd682f
Revises: f810e6a3c1df
Create Date: 2026-04-24 19:53:20.016195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cddcbebd682f'
down_revision: Union[str, Sequence[str], None] = 'f810e6a3c1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trends_runs', 'status',
               existing_type=postgresql.ENUM('started', 'completed', 'failed', name='runstatus'),
               type_=sa.Enum('started', 'completed', 'failed', name='runstatus', native_enum=False, length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trends_runs', 'status',
               existing_type=sa.Enum('started', 'completed', 'failed', name='runstatus', native_enum=False, length=20),
               type_=postgresql.ENUM('started', 'completed', 'failed', name='runstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
