"""Duplicates table - cluster id

Revision ID: d083e250e6a6
Revises: 682bae27645e
Create Date: 2026-04-18 20:05:46.782377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd083e250e6a6'
down_revision: Union[str, Sequence[str], None] = '682bae27645e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmp_duplicates', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.alter_column('tmp_duplicates', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('idx_tmp_duplicates_distance'), table_name='tmp_duplicates')
    op.drop_index(op.f('idx_tmp_duplicates_id'), table_name='tmp_duplicates')
    op.drop_index(op.f('idx_tmp_duplicates_id_distance'), table_name='tmp_duplicates')
    op.create_index(op.f('ix_tmp_duplicates_id'), 'tmp_duplicates', ['id'], unique=False)
    op.create_index(op.f('ix_tmp_duplicates_image_id1'), 'tmp_duplicates', ['image_id1'], unique=False)
    op.create_index(op.f('ix_tmp_duplicates_image_id2'), 'tmp_duplicates', ['image_id2'], unique=False)
    op.create_foreign_key(None, 'tmp_duplicates', 'images', ['image_id2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tmp_duplicates', 'images', ['image_id1'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tmp_duplicates', type_='foreignkey')
    op.drop_constraint(None, 'tmp_duplicates', type_='foreignkey')
    op.drop_index(op.f('ix_tmp_duplicates_image_id2'), table_name='tmp_duplicates')
    op.drop_index(op.f('ix_tmp_duplicates_image_id1'), table_name='tmp_duplicates')
    op.drop_index(op.f('ix_tmp_duplicates_id'), table_name='tmp_duplicates')
    op.create_index(op.f('idx_tmp_duplicates_id_distance'), 'tmp_duplicates', [sa.literal_column('id DESC'), 'distance'], unique=False)
    op.create_index(op.f('idx_tmp_duplicates_id'), 'tmp_duplicates', [sa.literal_column('id DESC')], unique=False)
    op.create_index(op.f('idx_tmp_duplicates_distance'), 'tmp_duplicates', ['distance'], unique=False)
    op.alter_column('tmp_duplicates', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('tmp_duplicates', 'cluster_id')
    # ### end Alembic commands ###
