"""Trends sourcing models - fix - remove

Revision ID: ed163efa0fa9
Revises: cddcbebd682f
Create Date: 2026-04-24 23:16:02.605231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed163efa0fa9'
down_revision: Union[str, Sequence[str], None] = 'cddcbebd682f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends_run_results')
    op.drop_table('trends_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends_run_results',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trends_runs.run_id'], name=op.f('trends_run_results_run_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['feed_sources.id'], name=op.f('trends_run_results_source_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trends_run_results_pkey'))
    )
    op.create_table('trends_runs',
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('trends_runs_pkey'))
    )
    # ### end Alembic commands ###
