"""Trends sourcing models - fix run status

Revision ID: f810e6a3c1df
Revises: fb26ce64e8b5
Create Date: 2026-04-24 19:33:00.207720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f810e6a3c1df'
down_revision: Union[str, Sequence[str], None] = 'fb26ce64e8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
