"""Trends sourcing models - add run status

Revision ID: fb26ce64e8b5
Revises: 6ad13a6f99bb
Create Date: 2026-04-24 18:55:31.867226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb26ce64e8b5'
down_revision: Union[str, Sequence[str], None] = '6ad13a6f99bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    runstatus = sa.Enum('started', 'completed', 'failed', name='runstatus')
    runstatus.create(op.get_bind())  # create the PG type first

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends_runs', sa.Column('status', sa.Enum('started', 'completed', 'failed', name='runstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends_runs', 'status')
    # ### end Alembic commands ###

    sa.Enum(name='runstatus').drop(op.get_bind())
