"""add_ocr_lemmas_table

Revision ID: ffd5c2d55945
Revises: a3c5a66c01c0
Create Date: 2026-07-21 20:36:04.869871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd5c2d55945'
down_revision: Union[str, Sequence[str], None] = 'a3c5a66c01c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_lemmas',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', 'lemma')
    )
    op.create_index('ix_ocr_lemmas_lemma', 'ocr_lemmas', ['lemma'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ocr_lemmas_lemma', table_name='ocr_lemmas')
    op.drop_table('ocr_lemmas')
    # ### end Alembic commands ###
